Delete key pair
dome9/cloud-bots pull request #65
Opened 2020-11-18 10:23 UTC by liranzu

Finished code review

2020-11-22 22:23 UTC, doronzil requested changes

2020-11-22 22:23 UTC, doronzil commented on bots/delete_key_pair.py
> +        text_output = "Keypair deleted: %s \n" % keypair
Please change to "Keypair %s was deleted successfully \n" % keypair

2020-11-24 13:25 UTC, doronzil requested changes

2020-11-24 13:25 UTC, doronzil commented on bots/ec2_delete_key_pair.py
> +        text_output = "Keypair %s was deleted successfully\n" % keypair
please use this pattern to print:
text_output = f'Keypair {keypair} was deleted successfully.\n'

2020-11-24 15:31 UTC, RavidAtias requested changes

2020-11-24 15:31 UTC, RavidAtias commented on bots/ec2_delete_key_pair.py
> +    except ClientError as e:
You don't need two exceptions, find out what is the exception of the API call and use it

2020-11-25 08:28 UTC, doronzil approved these changes

2020-11-30 10:32 UTC, RavidAtias approved these changes

2020-12-01 13:01 UTC, doronzil approved these changes

2020-12-01 13:02 UTC, merged